version: '3.8'
services:
  next_role_db:
    image: postgres:16-alpine3.19
    command: postgres -c 'max_connections=2000'
    container_name: next_role_db
    hostname: next_role_db
    restart: always
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=rqQoF792aMFAAftP9nse
      - POSTGRES_DB=next_role_db
    ports:
      - "6432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - internal_net
networks:
  internal_net:
    external: true
